# Generated by Django 4.1.2 on 2023-03-12 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_rename_cuidad_registros_ciudad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registros',
            name='correo',
            field=models.CharField(max_length=40),
        ),
    ]
